kubernetes:
  namespace: default
  name: test
  num_groups: 2
  ps_replicas: 1
  worker_replicas_each_group: [2,2]
tensorflow:
  user_model_file: example_user_model.py
  learning_rate: 0.01
  max_step: 1e5
  batch_size: 128
  optimizer: sgd
  
